	.align 2
DirectSoundWaveData_sc88pro_glockenspiel::
	.incbin "build/sound/direct_sound_samples/sc88pro_glockenspiel.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_organ2::
	.incbin "build/sound/direct_sound_samples/sc88pro_organ2.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_fretless_bass::
	.incbin "build/sound/direct_sound_samples/sc88pro_fretless_bass.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_slap_bass::
	.incbin "build/sound/direct_sound_samples/sc88pro_slap_bass.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_synth_bass::
	.incbin "build/sound/direct_sound_samples/sc88pro_synth_bass.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani::
	.incbin "build/sound/direct_sound_samples/sc88pro_timpani.aif.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "build/sound/direct_sound_samples/classical_choir_voice_ahhs.aif.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "build/sound/direct_sound_samples/sd90_classical_oboe.aif.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "build/sound/direct_sound_samples/unused_sd90_oboe.aif.bin"

	.align 2
DirectSoundWaveData_unused_guitar_separates_power_chord::
	.incbin "build/sound/direct_sound_samples/unused_guitar_separates_power_chord.aif.bin"

	.align 2
DirectSoundWaveData_unused_sc88pro_unison_slap::
	.incbin "build/sound/direct_sound_samples/unused_sc88pro_unison_slap.aif.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "build/sound/direct_sound_samples/unknown_snare.aif.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_ohtsuzumi::
	.incbin "build/sound/direct_sound_samples/ethnic_flavours_ohtsuzumi.aif.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_hyoushigi::
	.incbin "build/sound/direct_sound_samples/ethnic_flavours_hyoushigi.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_kick::
	.incbin "build/sound/direct_sound_samples/sc88pro_rnd_kick.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_snare::
	.incbin "build/sound/direct_sound_samples/sc88pro_rnd_snare.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_tr909_hand_clap::
	.incbin "build/sound/direct_sound_samples/sc88pro_tr909_hand_clap.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_snare::
	.incbin "build/sound/direct_sound_samples/sc88pro_orchestra_snare.aif.bin"

	.align 2
DirectSoundWaveData_unused_sc55_tom::
	.incbin "build/sound/direct_sound_samples/unused_sc55_tom.aif.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "build/sound/direct_sound_samples/unknown_close_hihat.aif.bin"

	.align 2
DirectSoundWaveData_unknown_open_hihat::
	.incbin "build/sound/direct_sound_samples/unknown_open_hihat.aif.bin"

	.align 2
DirectSoundWaveData_unknown_bell::
	.incbin "build/sound/direct_sound_samples/unknown_bell.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_tambourine::
	.incbin "build/sound/direct_sound_samples/sc88pro_tambourine.aif.bin"

	.align 2
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "build/sound/direct_sound_samples/trinity_cymbal_crash.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_cymbal_crash::
	.incbin "build/sound/direct_sound_samples/sc88pro_orchestra_cymbal_crash.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_mute_high_conga::
	.incbin "build/sound/direct_sound_samples/sc88pro_mute_high_conga.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_open_low_conga::
	.incbin "build/sound/direct_sound_samples/sc88pro_open_low_conga.aif.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "build/sound/direct_sound_samples/drum_and_percussion_kick.aif.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "build/sound/direct_sound_samples/sd90_solo_snare.aif.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "build/sound/direct_sound_samples/sd90_ambient_tom.aif.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "build/sound/direct_sound_samples/dance_drums_ride_bell.aif.bin"

	.align 2
DirectSoundWaveData_sd90_cowbell::
	.incbin "build/sound/direct_sound_samples/sd90_cowbell.aif.bin"

	.align 2
DirectSoundWaveData_unused_heart_of_asia_indian_drum::
	.incbin "build/sound/direct_sound_samples/unused_heart_of_asia_indian_drum.aif.bin"

	.align 2
DirectSoundWaveData_sd90_open_triangle::
	.incbin "build/sound/direct_sound_samples/sd90_open_triangle.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_jingle_bell::
	.incbin "build/sound/direct_sound_samples/sc88pro_jingle_bell.aif.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_atarigane::
	.incbin "build/sound/direct_sound_samples/ethnic_flavours_atarigane.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_taiko::
	.incbin "build/sound/direct_sound_samples/sc88pro_taiko.aif.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_kotsuzumi::
	.incbin "build/sound/direct_sound_samples/ethnic_flavours_kotsuzumi.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_48::
	.incbin "build/sound/direct_sound_samples/sc88pro_piano1_48.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_60::
	.incbin "build/sound/direct_sound_samples/sc88pro_piano1_60.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_72::
	.incbin "build/sound/direct_sound_samples/sc88pro_piano1_72.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_84::
	.incbin "build/sound/direct_sound_samples/sc88pro_piano1_84.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_60::
	.incbin "build/sound/direct_sound_samples/sc88pro_string_ensemble_60.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_72::
	.incbin "build/sound/direct_sound_samples/sc88pro_string_ensemble_72.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_84::
	.incbin "build/sound/direct_sound_samples/sc88pro_string_ensemble_84.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_60::
	.incbin "build/sound/direct_sound_samples/sc88pro_trumpet_60.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_72::
	.incbin "build/sound/direct_sound_samples/sc88pro_trumpet_72.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_84::
	.incbin "build/sound/direct_sound_samples/sc88pro_trumpet_84.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_39:: /*N.B.: These tuba samples are actually sampled at 36 and 48, then pitched up*/
	.incbin "build/sound/direct_sound_samples/sc88pro_tuba_39.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_51::
	.incbin "build/sound/direct_sound_samples/sc88pro_tuba_51.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_60::
	.incbin "build/sound/direct_sound_samples/sc88pro_french_horn_60.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_72::
	.incbin "build/sound/direct_sound_samples/sc88pro_french_horn_72.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_flute::
	.incbin "build/sound/direct_sound_samples/sc88pro_flute.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_fingered_bass::
	.incbin "build/sound/direct_sound_samples/sc88pro_fingered_bass.aif.bin"

	.align 2
DirectSoundWaveData_unknown_koto_high::
	.incbin "build/sound/direct_sound_samples/unknown_koto_high.aif.bin"

	.align 2
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "build/sound/direct_sound_samples/sd90_classical_shakuhachi.aif.bin"

	.align 2
DirectSoundWaveData_unknown_koto_low::
	.incbin "build/sound/direct_sound_samples/unknown_koto_low.aif.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "build/sound/direct_sound_samples/sd90_classical_overdrive_guitar.aif.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "build/sound/direct_sound_samples/sd90_classical_distortion_guitar_high.aif.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "build/sound/direct_sound_samples/sd90_classical_distortion_guitar_low.aif.bin"

	.align 2
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "build/sound/direct_sound_samples/heart_of_asia_gamelan.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_low::
	.incbin "build/sound/direct_sound_samples/sc88pro_church_organ3_low.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_high::
	.incbin "build/sound/direct_sound_samples/sc88pro_church_organ3_high.aif.bin"

	.align 2
DirectSoundWaveData_unknown_female_voice::
	.incbin "build/sound/direct_sound_samples/unknown_female_voice.aif.bin"

	.align 2
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "build/sound/direct_sound_samples/unused_unknown_male_voice.aif.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "build/sound/direct_sound_samples/sd90_classical_detuned_ep1_low.aif.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "build/sound/direct_sound_samples/sd90_classical_detuned_ep1_high.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani_with_snare::
	.incbin "build/sound/direct_sound_samples/sc88pro_timpani_with_snare.aif.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "build/sound/direct_sound_samples/unknown_synth_snare.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_square_wave::
	.incbin "build/sound/direct_sound_samples/sc88pro_square_wave.aif.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "build/sound/direct_sound_samples/bicycle_bell.aif.bin"

	.align 2
DirectSoundWaveData_unknown_1::
	.incbin "build/sound/direct_sound_samples/unknown_01.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_pizzicato_strings::
	.incbin "build/sound/direct_sound_samples/sc88pro_pizzicato_strings.aif.bin"

	.align 2
DirectSoundWaveData_unknown_2::
	.incbin "build/sound/direct_sound_samples/unknown_02.aif.bin"

	.align 2
DirectSoundWaveData_unknown_3::
	.incbin "build/sound/direct_sound_samples/unknown_03.aif.bin"

	.align 2
DirectSoundWaveData_unknown_4::
	.incbin "build/sound/direct_sound_samples/unknown_04.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_wind::
	.incbin "build/sound/direct_sound_samples/sc88pro_wind.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_bubbles::
	.incbin "build/sound/direct_sound_samples/sc88pro_bubbles.aif.bin"

	.align 2
DirectSoundWaveData_unknown_5::
	.incbin "build/sound/direct_sound_samples/unknown_05.aif.bin"

	.align 2
DirectSoundWaveData_unknown_6::
	.incbin "build/sound/direct_sound_samples/unknown_06.aif.bin"

	.align 2
DirectSoundWaveData_trinity_30303_mega_bass::
	.incbin "build/sound/direct_sound_samples/trinity_30303_mega_bass.aif.bin"

	.align 2
DirectSoundWaveData_unknown_7::
	.incbin "build/sound/direct_sound_samples/unknown_07.aif.bin"

	.align 2
DirectSoundWaveData_unknown_8::
	.incbin "build/sound/direct_sound_samples/unknown_08.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_tubular_bell::
	.incbin "build/sound/direct_sound_samples/sc88pro_tubular_bell.aif.bin"

	.align 2
DirectSoundWaveData_unknown_9::
	.incbin "build/sound/direct_sound_samples/unknown_09.aif.bin"

	.align 2
DirectSoundWaveData_trinity_big_boned::
	.incbin "build/sound/direct_sound_samples/trinity_big_boned.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_harp::
	.incbin "build/sound/direct_sound_samples/sc88pro_harp.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_xylophone::
	.incbin "build/sound/direct_sound_samples/sc88pro_xylophone.aif.bin"

	.align 2
DirectSoundWaveData_unknown_10::
	.incbin "build/sound/direct_sound_samples/unknown_10.aif.bin"

	.align 2
DirectSoundWaveData_unknown_11::
	.incbin "build/sound/direct_sound_samples/unknown_11.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion::
	.incbin "build/sound/direct_sound_samples/sc88pro_accordion.aif.bin"

	.align 2
DirectSoundWaveData_unknown_12::
	.incbin "build/sound/direct_sound_samples/unknown_12.aif.bin"

	.align 2
DirectSoundWaveData_unknown_13::
	.incbin "build/sound/direct_sound_samples/unknown_13.aif.bin"

	.align 2
DirectSoundWaveData_unknown_14::
	.incbin "build/sound/direct_sound_samples/unknown_14.aif.bin"

	.align 2
DirectSoundWaveData_unknown_15::
	.incbin "build/sound/direct_sound_samples/unknown_15.aif.bin"

	.align 2
DirectSoundWaveData_unknown_16::
	.incbin "build/sound/direct_sound_samples/unknown_16.aif.bin"

	.align 2
DirectSoundWaveData_unknown_17::
	.incbin "build/sound/direct_sound_samples/unknown_17.aif.bin"

	.align 2
Cry_Bulbasaur::
	.incbin "build/sound/direct_sound_samples/cries/bulbasaur.aif.bin"

	.align 2
Cry_Ivysaur::
	.incbin "build/sound/direct_sound_samples/cries/ivysaur.aif.bin"

	.align 2
Cry_Venusaur::
	.incbin "build/sound/direct_sound_samples/cries/venusaur.aif.bin"

	.align 2
Cry_Charmander::
	.incbin "build/sound/direct_sound_samples/cries/charmander.aif.bin"

	.align 2
Cry_Charmeleon::
	.incbin "build/sound/direct_sound_samples/cries/charmeleon.aif.bin"

	.align 2
Cry_Charizard::
	.incbin "build/sound/direct_sound_samples/cries/charizard.aif.bin"

	.align 2
Cry_Squirtle::
	.incbin "build/sound/direct_sound_samples/cries/squirtle.aif.bin"

	.align 2
Cry_Wartortle::
	.incbin "build/sound/direct_sound_samples/cries/wartortle.aif.bin"

	.align 2
Cry_Blastoise::
	.incbin "build/sound/direct_sound_samples/cries/blastoise.aif.bin"

	.align 2
Cry_Caterpie::
	.incbin "build/sound/direct_sound_samples/cries/caterpie.aif.bin"

	.align 2
Cry_Metapod::
	.incbin "build/sound/direct_sound_samples/cries/metapod.aif.bin"

	.align 2
Cry_Butterfree::
	.incbin "build/sound/direct_sound_samples/cries/butterfree.aif.bin"

	.align 2
Cry_Weedle::
	.incbin "build/sound/direct_sound_samples/cries/weedle.aif.bin"

	.align 2
Cry_Kakuna::
	.incbin "build/sound/direct_sound_samples/cries/kakuna.aif.bin"

	.align 2
Cry_Beedrill::
	.incbin "build/sound/direct_sound_samples/cries/beedrill.aif.bin"

	.align 2
Cry_Pidgey::
	.incbin "build/sound/direct_sound_samples/cries/pidgey.aif.bin"

	.align 2
Cry_Pidgeotto::
	.incbin "build/sound/direct_sound_samples/cries/pidgeotto.aif.bin"

	.align 2
Cry_Pidgeot::
	.incbin "build/sound/direct_sound_samples/cries/pidgeot.aif.bin"

	.align 2
Cry_Rattata::
	.incbin "build/sound/direct_sound_samples/cries/rattata.aif.bin"

	.align 2
Cry_Raticate::
	.incbin "build/sound/direct_sound_samples/cries/raticate.aif.bin"

	.align 2
Cry_Spearow::
	.incbin "build/sound/direct_sound_samples/cries/spearow.aif.bin"

	.align 2
Cry_Fearow::
	.incbin "build/sound/direct_sound_samples/cries/fearow.aif.bin"

	.align 2
Cry_Ekans::
	.incbin "build/sound/direct_sound_samples/cries/ekans.aif.bin"

	.align 2
Cry_Arbok::
	.incbin "build/sound/direct_sound_samples/cries/arbok.aif.bin"

	.align 2
Cry_Pikachu::
	.incbin "build/sound/direct_sound_samples/cries/pikachu.aif.bin"

	.align 2
Cry_Raichu::
	.incbin "build/sound/direct_sound_samples/cries/raichu.aif.bin"

	.align 2
Cry_Sandshrew::
	.incbin "build/sound/direct_sound_samples/cries/sandshrew.aif.bin"

	.align 2
Cry_Sandslash::
	.incbin "build/sound/direct_sound_samples/cries/sandslash.aif.bin"

	.align 2
Cry_NidoranF::
	.incbin "build/sound/direct_sound_samples/cries/nidoran_f.aif.bin"

	.align 2
Cry_Nidorina::
	.incbin "build/sound/direct_sound_samples/cries/nidorina.aif.bin"

	.align 2
Cry_Nidoqueen::
	.incbin "build/sound/direct_sound_samples/cries/nidoqueen.aif.bin"

	.align 2
Cry_NidoranM::
	.incbin "build/sound/direct_sound_samples/cries/nidoran_m.aif.bin"

	.align 2
Cry_Nidorino::
	.incbin "build/sound/direct_sound_samples/cries/nidorino.aif.bin"

	.align 2
Cry_Nidoking::
	.incbin "build/sound/direct_sound_samples/cries/nidoking.aif.bin"

	.align 2
Cry_Clefairy::
	.incbin "build/sound/direct_sound_samples/cries/clefairy.aif.bin"

	.align 2
Cry_Clefable::
	.incbin "build/sound/direct_sound_samples/cries/clefable.aif.bin"

	.align 2
Cry_Vulpix::
	.incbin "build/sound/direct_sound_samples/cries/vulpix.aif.bin"

	.align 2
Cry_Ninetales::
	.incbin "build/sound/direct_sound_samples/cries/ninetales.aif.bin"

	.align 2
Cry_Jigglypuff::
	.incbin "build/sound/direct_sound_samples/cries/jigglypuff.aif.bin"

	.align 2
Cry_Wigglytuff::
	.incbin "build/sound/direct_sound_samples/cries/wigglytuff.aif.bin"

	.align 2
Cry_Zubat::
	.incbin "build/sound/direct_sound_samples/cries/zubat.aif.bin"

	.align 2
Cry_Golbat::
	.incbin "build/sound/direct_sound_samples/cries/golbat.aif.bin"

	.align 2
Cry_Oddish::
	.incbin "build/sound/direct_sound_samples/cries/oddish.aif.bin"

	.align 2
Cry_Gloom::
	.incbin "build/sound/direct_sound_samples/cries/gloom.aif.bin"

	.align 2
Cry_Vileplume::
	.incbin "build/sound/direct_sound_samples/cries/vileplume.aif.bin"

	.align 2
Cry_Paras::
	.incbin "build/sound/direct_sound_samples/cries/paras.aif.bin"

	.align 2
Cry_Parasect::
	.incbin "build/sound/direct_sound_samples/cries/parasect.aif.bin"

	.align 2
Cry_Venonat::
	.incbin "build/sound/direct_sound_samples/cries/venonat.aif.bin"

	.align 2
Cry_Venomoth::
	.incbin "build/sound/direct_sound_samples/cries/venomoth.aif.bin"

	.align 2
Cry_Diglett::
	.incbin "build/sound/direct_sound_samples/cries/diglett.aif.bin"

	.align 2
Cry_Dugtrio::
	.incbin "build/sound/direct_sound_samples/cries/dugtrio.aif.bin"

	.align 2
Cry_Meowth::
	.incbin "build/sound/direct_sound_samples/cries/meowth.aif.bin"

	.align 2
Cry_Persian::
	.incbin "build/sound/direct_sound_samples/cries/persian.aif.bin"

	.align 2
Cry_Psyduck::
	.incbin "build/sound/direct_sound_samples/cries/psyduck.aif.bin"

	.align 2
Cry_Golduck::
	.incbin "build/sound/direct_sound_samples/cries/golduck.aif.bin"

	.align 2
Cry_Mankey::
	.incbin "build/sound/direct_sound_samples/cries/mankey.aif.bin"

	.align 2
Cry_Primeape::
	.incbin "build/sound/direct_sound_samples/cries/primeape.aif.bin"

	.align 2
Cry_Growlithe::
	.incbin "build/sound/direct_sound_samples/cries/growlithe.aif.bin"

	.align 2
Cry_Arcanine::
	.incbin "build/sound/direct_sound_samples/cries/arcanine.aif.bin"

	.align 2
Cry_Poliwag::
	.incbin "build/sound/direct_sound_samples/cries/poliwag.aif.bin"

	.align 2
Cry_Poliwhirl::
	.incbin "build/sound/direct_sound_samples/cries/poliwhirl.aif.bin"

	.align 2
Cry_Poliwrath::
	.incbin "build/sound/direct_sound_samples/cries/poliwrath.aif.bin"

	.align 2
Cry_Abra::
	.incbin "build/sound/direct_sound_samples/cries/abra.aif.bin"

	.align 2
Cry_Kadabra::
	.incbin "build/sound/direct_sound_samples/cries/kadabra.aif.bin"

	.align 2
Cry_Alakazam::
	.incbin "build/sound/direct_sound_samples/cries/alakazam.aif.bin"

	.align 2
Cry_Machop::
	.incbin "build/sound/direct_sound_samples/cries/machop.aif.bin"

	.align 2
Cry_Machoke::
	.incbin "build/sound/direct_sound_samples/cries/machoke.aif.bin"

	.align 2
Cry_Machamp::
	.incbin "build/sound/direct_sound_samples/cries/machamp.aif.bin"

	.align 2
Cry_Bellsprout::
	.incbin "build/sound/direct_sound_samples/cries/bellsprout.aif.bin"

	.align 2
Cry_Weepinbell::
	.incbin "build/sound/direct_sound_samples/cries/weepinbell.aif.bin"

	.align 2
Cry_Victreebel::
	.incbin "build/sound/direct_sound_samples/cries/victreebel.aif.bin"

	.align 2
Cry_Tentacool::
	.incbin "build/sound/direct_sound_samples/cries/tentacool.aif.bin"

	.align 2
Cry_Tentacruel::
	.incbin "build/sound/direct_sound_samples/cries/tentacruel.aif.bin"

	.align 2
Cry_Geodude::
	.incbin "build/sound/direct_sound_samples/cries/geodude.aif.bin"

	.align 2
Cry_Graveler::
	.incbin "build/sound/direct_sound_samples/cries/graveler.aif.bin"

	.align 2
Cry_Golem::
	.incbin "build/sound/direct_sound_samples/cries/golem.aif.bin"

	.align 2
Cry_Ponyta::
	.incbin "build/sound/direct_sound_samples/cries/ponyta.aif.bin"

	.align 2
Cry_Rapidash::
	.incbin "build/sound/direct_sound_samples/cries/rapidash.aif.bin"

	.align 2
Cry_Slowpoke::
	.incbin "build/sound/direct_sound_samples/cries/slowpoke.aif.bin"

	.align 2
Cry_Slowbro::
	.incbin "build/sound/direct_sound_samples/cries/slowbro.aif.bin"

	.align 2
Cry_Magnemite::
	.incbin "build/sound/direct_sound_samples/cries/magnemite.aif.bin"

	.align 2
Cry_Magneton::
	.incbin "build/sound/direct_sound_samples/cries/magneton.aif.bin"

	.align 2
Cry_Farfetchd::
	.incbin "build/sound/direct_sound_samples/cries/farfetchd.aif.bin"

	.align 2
Cry_Doduo::
	.incbin "build/sound/direct_sound_samples/cries/doduo.aif.bin"

	.align 2
Cry_Dodrio::
	.incbin "build/sound/direct_sound_samples/cries/dodrio.aif.bin"

	.align 2
Cry_Seel::
	.incbin "build/sound/direct_sound_samples/cries/seel.aif.bin"

	.align 2
Cry_Dewgong::
	.incbin "build/sound/direct_sound_samples/cries/dewgong.aif.bin"

	.align 2
Cry_Grimer::
	.incbin "build/sound/direct_sound_samples/cries/grimer.aif.bin"

	.align 2
Cry_Muk::
	.incbin "build/sound/direct_sound_samples/cries/muk.aif.bin"

	.align 2
Cry_Shellder::
	.incbin "build/sound/direct_sound_samples/cries/shellder.aif.bin"

	.align 2
Cry_Cloyster::
	.incbin "build/sound/direct_sound_samples/cries/cloyster.aif.bin"

	.align 2
Cry_Gastly::
	.incbin "build/sound/direct_sound_samples/cries/gastly.aif.bin"

	.align 2
Cry_Haunter::
	.incbin "build/sound/direct_sound_samples/cries/haunter.aif.bin"

	.align 2
Cry_Gengar::
	.incbin "build/sound/direct_sound_samples/cries/gengar.aif.bin"

	.align 2
Cry_Onix::
	.incbin "build/sound/direct_sound_samples/cries/onix.aif.bin"

	.align 2
Cry_Drowzee::
	.incbin "build/sound/direct_sound_samples/cries/drowzee.aif.bin"

	.align 2
Cry_Hypno::
	.incbin "build/sound/direct_sound_samples/cries/hypno.aif.bin"

	.align 2
Cry_Krabby::
	.incbin "build/sound/direct_sound_samples/cries/krabby.aif.bin"

	.align 2
Cry_Kingler::
	.incbin "build/sound/direct_sound_samples/cries/kingler.aif.bin"

	.align 2
Cry_Voltorb::
	.incbin "build/sound/direct_sound_samples/cries/voltorb.aif.bin"

	.align 2
Cry_Electrode::
	.incbin "build/sound/direct_sound_samples/cries/electrode.aif.bin"

	.align 2
Cry_Exeggcute::
	.incbin "build/sound/direct_sound_samples/cries/exeggcute.aif.bin"

	.align 2
Cry_Exeggutor::
	.incbin "build/sound/direct_sound_samples/cries/exeggutor.aif.bin"

	.align 2
Cry_Cubone::
	.incbin "build/sound/direct_sound_samples/cries/cubone.aif.bin"

	.align 2
Cry_Marowak::
	.incbin "build/sound/direct_sound_samples/cries/marowak.aif.bin"

	.align 2
Cry_Hitmonlee::
	.incbin "build/sound/direct_sound_samples/cries/hitmonlee.aif.bin"

	.align 2
Cry_Hitmonchan::
	.incbin "build/sound/direct_sound_samples/cries/hitmonchan.aif.bin"

	.align 2
Cry_Lickitung::
	.incbin "build/sound/direct_sound_samples/cries/lickitung.aif.bin"

	.align 2
Cry_Koffing::
	.incbin "build/sound/direct_sound_samples/cries/koffing.aif.bin"

	.align 2
Cry_Weezing::
	.incbin "build/sound/direct_sound_samples/cries/weezing.aif.bin"

	.align 2
Cry_Rhyhorn::
	.incbin "build/sound/direct_sound_samples/cries/rhyhorn.aif.bin"

	.align 2
Cry_Rhydon::
	.incbin "build/sound/direct_sound_samples/cries/rhydon.aif.bin"

	.align 2
Cry_Chansey::
	.incbin "build/sound/direct_sound_samples/cries/chansey.aif.bin"

	.align 2
Cry_Tangela::
	.incbin "build/sound/direct_sound_samples/cries/tangela.aif.bin"

	.align 2
Cry_Kangaskhan::
	.incbin "build/sound/direct_sound_samples/cries/kangaskhan.aif.bin"

	.align 2
Cry_Horsea::
	.incbin "build/sound/direct_sound_samples/cries/horsea.aif.bin"

	.align 2
Cry_Seadra::
	.incbin "build/sound/direct_sound_samples/cries/seadra.aif.bin"

	.align 2
Cry_Goldeen::
	.incbin "build/sound/direct_sound_samples/cries/goldeen.aif.bin"

	.align 2
Cry_Seaking::
	.incbin "build/sound/direct_sound_samples/cries/seaking.aif.bin"

	.align 2
Cry_Staryu::
	.incbin "build/sound/direct_sound_samples/cries/staryu.aif.bin"

	.align 2
Cry_Starmie::
	.incbin "build/sound/direct_sound_samples/cries/starmie.aif.bin"

	.align 2
Cry_MrMime::
	.incbin "build/sound/direct_sound_samples/cries/mr_mime.aif.bin"

	.align 2
Cry_Scyther::
	.incbin "build/sound/direct_sound_samples/cries/scyther.aif.bin"

	.align 2
Cry_Jynx::
	.incbin "build/sound/direct_sound_samples/cries/jynx.aif.bin"

	.align 2
Cry_Electabuzz::
	.incbin "build/sound/direct_sound_samples/cries/electabuzz.aif.bin"

	.align 2
Cry_Magmar::
	.incbin "build/sound/direct_sound_samples/cries/magmar.aif.bin"

	.align 2
Cry_Pinsir::
	.incbin "build/sound/direct_sound_samples/cries/pinsir.aif.bin"

	.align 2
Cry_Tauros::
	.incbin "build/sound/direct_sound_samples/cries/tauros.aif.bin"

	.align 2
Cry_Magikarp::
	.incbin "build/sound/direct_sound_samples/cries/magikarp.aif.bin"

	.align 2
Cry_Gyarados::
	.incbin "build/sound/direct_sound_samples/cries/gyarados.aif.bin"

	.align 2
Cry_Lapras::
	.incbin "build/sound/direct_sound_samples/cries/lapras.aif.bin"

	.align 2
Cry_Ditto::
	.incbin "build/sound/direct_sound_samples/cries/ditto.aif.bin"

	.align 2
Cry_Eevee::
	.incbin "build/sound/direct_sound_samples/cries/eevee.aif.bin"

	.align 2
Cry_Vaporeon::
	.incbin "build/sound/direct_sound_samples/cries/vaporeon.aif.bin"

	.align 2
Cry_Jolteon::
	.incbin "build/sound/direct_sound_samples/cries/jolteon.aif.bin"

	.align 2
Cry_Flareon::
	.incbin "build/sound/direct_sound_samples/cries/flareon.aif.bin"

	.align 2
Cry_Porygon::
	.incbin "build/sound/direct_sound_samples/cries/porygon.aif.bin"

	.align 2
Cry_Omanyte::
	.incbin "build/sound/direct_sound_samples/cries/omanyte.aif.bin"

	.align 2
Cry_Omastar::
	.incbin "build/sound/direct_sound_samples/cries/omastar.aif.bin"

	.align 2
Cry_Kabuto::
	.incbin "build/sound/direct_sound_samples/cries/kabuto.aif.bin"

	.align 2
Cry_Kabutops::
	.incbin "build/sound/direct_sound_samples/cries/kabutops.aif.bin"

	.align 2
Cry_Aerodactyl::
	.incbin "build/sound/direct_sound_samples/cries/aerodactyl.aif.bin"

	.align 2
Cry_Snorlax::
	.incbin "build/sound/direct_sound_samples/cries/snorlax.aif.bin"

	.align 2
Cry_Articuno::
	.incbin "build/sound/direct_sound_samples/cries/articuno.aif.bin"

	.align 2
Cry_Zapdos::
	.incbin "build/sound/direct_sound_samples/cries/zapdos.aif.bin"

	.align 2
Cry_Moltres::
	.incbin "build/sound/direct_sound_samples/cries/moltres.aif.bin"

	.align 2
Cry_Dratini::
	.incbin "build/sound/direct_sound_samples/cries/dratini.aif.bin"

	.align 2
Cry_Dragonair::
	.incbin "build/sound/direct_sound_samples/cries/dragonair.aif.bin"

	.align 2
Cry_Dragonite::
	.incbin "build/sound/direct_sound_samples/cries/dragonite.aif.bin"

	.align 2
Cry_Mewtwo::
	.incbin "build/sound/direct_sound_samples/cries/mewtwo.aif.bin"

	.align 2
Cry_Mew::
	.incbin "build/sound/direct_sound_samples/cries/mew.aif.bin"

	.align 2
Cry_Chikorita::
	.incbin "build/sound/direct_sound_samples/cries/chikorita.aif.bin"

	.align 2
Cry_Bayleef::
	.incbin "build/sound/direct_sound_samples/cries/bayleef.aif.bin"

	.align 2
Cry_Meganium::
	.incbin "build/sound/direct_sound_samples/cries/meganium.aif.bin"

	.align 2
Cry_Cyndaquil::
	.incbin "build/sound/direct_sound_samples/cries/cyndaquil.aif.bin"

	.align 2
Cry_Quilava::
	.incbin "build/sound/direct_sound_samples/cries/quilava.aif.bin"

	.align 2
Cry_Typhlosion::
	.incbin "build/sound/direct_sound_samples/cries/typhlosion.aif.bin"

	.align 2
Cry_Totodile::
	.incbin "build/sound/direct_sound_samples/cries/totodile.aif.bin"

	.align 2
Cry_Croconaw::
	.incbin "build/sound/direct_sound_samples/cries/croconaw.aif.bin"

	.align 2
Cry_Feraligatr::
	.incbin "build/sound/direct_sound_samples/cries/feraligatr.aif.bin"

	.align 2
Cry_Sentret::
	.incbin "build/sound/direct_sound_samples/cries/sentret.aif.bin"

	.align 2
Cry_Furret::
	.incbin "build/sound/direct_sound_samples/cries/furret.aif.bin"

	.align 2
Cry_Hoothoot::
	.incbin "build/sound/direct_sound_samples/cries/hoothoot.aif.bin"

	.align 2
Cry_Noctowl::
	.incbin "build/sound/direct_sound_samples/cries/noctowl.aif.bin"

	.align 2
Cry_Ledyba::
	.incbin "build/sound/direct_sound_samples/cries/ledyba.aif.bin"

	.align 2
Cry_Ledian::
	.incbin "build/sound/direct_sound_samples/cries/ledian.aif.bin"

	.align 2
Cry_Spinarak::
	.incbin "build/sound/direct_sound_samples/cries/spinarak.aif.bin"

	.align 2
Cry_Ariados::
	.incbin "build/sound/direct_sound_samples/cries/ariados.aif.bin"

	.align 2
Cry_Crobat::
	.incbin "build/sound/direct_sound_samples/cries/crobat.aif.bin"

	.align 2
Cry_Chinchou::
	.incbin "build/sound/direct_sound_samples/cries/chinchou.aif.bin"

	.align 2
Cry_Lanturn::
	.incbin "build/sound/direct_sound_samples/cries/lanturn.aif.bin"

	.align 2
Cry_Pichu::
	.incbin "build/sound/direct_sound_samples/cries/pichu.aif.bin"

	.align 2
Cry_Cleffa::
	.incbin "build/sound/direct_sound_samples/cries/cleffa.aif.bin"

	.align 2
Cry_Igglybuff::
	.incbin "build/sound/direct_sound_samples/cries/igglybuff.aif.bin"

	.align 2
Cry_Togepi::
	.incbin "build/sound/direct_sound_samples/cries/togepi.aif.bin"

	.align 2
Cry_Togetic::
	.incbin "build/sound/direct_sound_samples/cries/togetic.aif.bin"

	.align 2
Cry_Natu::
	.incbin "build/sound/direct_sound_samples/cries/natu.aif.bin"

	.align 2
Cry_Xatu::
	.incbin "build/sound/direct_sound_samples/cries/xatu.aif.bin"

	.align 2
Cry_Mareep::
	.incbin "build/sound/direct_sound_samples/cries/mareep.aif.bin"

	.align 2
Cry_Flaaffy::
	.incbin "build/sound/direct_sound_samples/cries/flaaffy.aif.bin"

	.align 2
Cry_Ampharos::
	.incbin "build/sound/direct_sound_samples/cries/ampharos.aif.bin"

	.align 2
Cry_Bellossom::
	.incbin "build/sound/direct_sound_samples/cries/bellossom.aif.bin"

	.align 2
Cry_Marill::
	.incbin "build/sound/direct_sound_samples/cries/marill.aif.bin"

	.align 2
Cry_Azumarill::
	.incbin "build/sound/direct_sound_samples/cries/azumarill.aif.bin"

	.align 2
Cry_Sudowoodo::
	.incbin "build/sound/direct_sound_samples/cries/sudowoodo.aif.bin"

	.align 2
Cry_Politoed::
	.incbin "build/sound/direct_sound_samples/cries/politoed.aif.bin"

	.align 2
Cry_Hoppip::
	.incbin "build/sound/direct_sound_samples/cries/hoppip.aif.bin"

	.align 2
Cry_Skiploom::
	.incbin "build/sound/direct_sound_samples/cries/skiploom.aif.bin"

	.align 2
Cry_Jumpluff::
	.incbin "build/sound/direct_sound_samples/cries/jumpluff.aif.bin"

	.align 2
Cry_Aipom::
	.incbin "build/sound/direct_sound_samples/cries/aipom.aif.bin"

	.align 2
Cry_Sunkern::
	.incbin "build/sound/direct_sound_samples/cries/sunkern.aif.bin"

	.align 2
Cry_Sunflora::
	.incbin "build/sound/direct_sound_samples/cries/sunflora.aif.bin"

	.align 2
Cry_Yanma::
	.incbin "build/sound/direct_sound_samples/cries/yanma.aif.bin"

	.align 2
Cry_Wooper::
	.incbin "build/sound/direct_sound_samples/cries/wooper.aif.bin"

	.align 2
Cry_Quagsire::
	.incbin "build/sound/direct_sound_samples/cries/quagsire.aif.bin"

	.align 2
Cry_Espeon::
	.incbin "build/sound/direct_sound_samples/cries/espeon.aif.bin"

	.align 2
Cry_Umbreon::
	.incbin "build/sound/direct_sound_samples/cries/umbreon.aif.bin"

	.align 2
Cry_Murkrow::
	.incbin "build/sound/direct_sound_samples/cries/murkrow.aif.bin"

	.align 2
Cry_Slowking::
	.incbin "build/sound/direct_sound_samples/cries/slowking.aif.bin"

	.align 2
Cry_Misdreavus::
	.incbin "build/sound/direct_sound_samples/cries/misdreavus.aif.bin"

	.align 2
Cry_Unown::
	.incbin "build/sound/direct_sound_samples/cries/unown.aif.bin"

	.align 2
Cry_Wobbuffet::
	.incbin "build/sound/direct_sound_samples/cries/wobbuffet.aif.bin"

	.align 2
Cry_Girafarig::
	.incbin "build/sound/direct_sound_samples/cries/girafarig.aif.bin"

	.align 2
Cry_Pineco::
	.incbin "build/sound/direct_sound_samples/cries/pineco.aif.bin"

	.align 2
Cry_Forretress::
	.incbin "build/sound/direct_sound_samples/cries/forretress.aif.bin"

	.align 2
Cry_Dunsparce::
	.incbin "build/sound/direct_sound_samples/cries/dunsparce.aif.bin"

	.align 2
Cry_Gligar::
	.incbin "build/sound/direct_sound_samples/cries/gligar.aif.bin"

	.align 2
Cry_Steelix::
	.incbin "build/sound/direct_sound_samples/cries/steelix.aif.bin"

	.align 2
Cry_Snubbull::
	.incbin "build/sound/direct_sound_samples/cries/snubbull.aif.bin"

	.align 2
Cry_Granbull::
	.incbin "build/sound/direct_sound_samples/cries/granbull.aif.bin"

	.align 2
Cry_Qwilfish::
	.incbin "build/sound/direct_sound_samples/cries/qwilfish.aif.bin"

	.align 2
Cry_Scizor::
	.incbin "build/sound/direct_sound_samples/cries/scizor.aif.bin"

	.align 2
Cry_Shuckle::
	.incbin "build/sound/direct_sound_samples/cries/shuckle.aif.bin"

	.align 2
Cry_Heracross::
	.incbin "build/sound/direct_sound_samples/cries/heracross.aif.bin"

	.align 2
Cry_Sneasel::
	.incbin "build/sound/direct_sound_samples/cries/sneasel.aif.bin"

	.align 2
Cry_Teddiursa::
	.incbin "build/sound/direct_sound_samples/cries/teddiursa.aif.bin"

	.align 2
Cry_Ursaring::
	.incbin "build/sound/direct_sound_samples/cries/ursaring.aif.bin"

	.align 2
Cry_Slugma::
	.incbin "build/sound/direct_sound_samples/cries/slugma.aif.bin"

	.align 2
Cry_Magcargo::
	.incbin "build/sound/direct_sound_samples/cries/magcargo.aif.bin"

	.align 2
Cry_Swinub::
	.incbin "build/sound/direct_sound_samples/cries/swinub.aif.bin"

	.align 2
Cry_Piloswine::
	.incbin "build/sound/direct_sound_samples/cries/piloswine.aif.bin"

	.align 2
Cry_Corsola::
	.incbin "build/sound/direct_sound_samples/cries/corsola.aif.bin"

	.align 2
Cry_Remoraid::
	.incbin "build/sound/direct_sound_samples/cries/remoraid.aif.bin"

	.align 2
Cry_Octillery::
	.incbin "build/sound/direct_sound_samples/cries/octillery.aif.bin"

	.align 2
Cry_Delibird::
	.incbin "build/sound/direct_sound_samples/cries/delibird.aif.bin"

	.align 2
Cry_Mantine::
	.incbin "build/sound/direct_sound_samples/cries/mantine.aif.bin"

	.align 2
Cry_Skarmory::
	.incbin "build/sound/direct_sound_samples/cries/skarmory.aif.bin"

	.align 2
Cry_Houndour::
	.incbin "build/sound/direct_sound_samples/cries/houndour.aif.bin"

	.align 2
Cry_Houndoom::
	.incbin "build/sound/direct_sound_samples/cries/houndoom.aif.bin"

	.align 2
Cry_Kingdra::
	.incbin "build/sound/direct_sound_samples/cries/kingdra.aif.bin"

	.align 2
Cry_Phanpy::
	.incbin "build/sound/direct_sound_samples/cries/phanpy.aif.bin"

	.align 2
Cry_Donphan::
	.incbin "build/sound/direct_sound_samples/cries/donphan.aif.bin"

	.align 2
Cry_Porygon2::
	.incbin "build/sound/direct_sound_samples/cries/porygon2.aif.bin"

	.align 2
Cry_Stantler::
	.incbin "build/sound/direct_sound_samples/cries/stantler.aif.bin"

	.align 2
Cry_Smeargle::
	.incbin "build/sound/direct_sound_samples/cries/smeargle.aif.bin"

	.align 2
Cry_Tyrogue::
	.incbin "build/sound/direct_sound_samples/cries/tyrogue.aif.bin"

	.align 2
Cry_Hitmontop::
	.incbin "build/sound/direct_sound_samples/cries/hitmontop.aif.bin"

	.align 2
Cry_Smoochum::
	.incbin "build/sound/direct_sound_samples/cries/smoochum.aif.bin"

	.align 2
Cry_Elekid::
	.incbin "build/sound/direct_sound_samples/cries/elekid.aif.bin"

	.align 2
Cry_Magby::
	.incbin "build/sound/direct_sound_samples/cries/magby.aif.bin"

	.align 2
Cry_Miltank::
	.incbin "build/sound/direct_sound_samples/cries/miltank.aif.bin"

	.align 2
Cry_Blissey::
	.incbin "build/sound/direct_sound_samples/cries/blissey.aif.bin"

	.align 2
Cry_Raikou::
	.incbin "build/sound/direct_sound_samples/cries/raikou.aif.bin"

	.align 2
Cry_Entei::
	.incbin "build/sound/direct_sound_samples/cries/entei.aif.bin"

	.align 2
Cry_Suicune::
	.incbin "build/sound/direct_sound_samples/cries/suicune.aif.bin"

	.align 2
Cry_Larvitar::
	.incbin "build/sound/direct_sound_samples/cries/larvitar.aif.bin"

	.align 2
Cry_Pupitar::
	.incbin "build/sound/direct_sound_samples/cries/pupitar.aif.bin"

	.align 2
Cry_Tyranitar::
	.incbin "build/sound/direct_sound_samples/cries/tyranitar.aif.bin"

	.align 2
Cry_Lugia::
	.incbin "build/sound/direct_sound_samples/cries/lugia.aif.bin"

	.align 2
Cry_HoOh::
	.incbin "build/sound/direct_sound_samples/cries/ho_oh.aif.bin"

	.align 2
Cry_Celebi::
	.incbin "build/sound/direct_sound_samples/cries/celebi.aif.bin"

	.align 2
Cry_Kecleon::
	.incbin "build/sound/direct_sound_samples/cries/kecleon.aif.bin"

	.align 2
Cry_Roselia::
	.incbin "build/sound/direct_sound_samples/cries/roselia.aif.bin"

	.align 2
Cry_Torkoal::
	.incbin "build/sound/direct_sound_samples/cries/torkoal.aif.bin"

	.align 2
Cry_Electrike::
	.incbin "build/sound/direct_sound_samples/cries/electrike.aif.bin"

	.align 2
Cry_Manectric::
	.incbin "build/sound/direct_sound_samples/cries/manectric.aif.bin"

	.align 2
Cry_Duskull::
	.incbin "build/sound/direct_sound_samples/cries/duskull.aif.bin"

	.align 2
Cry_Latias::
	.incbin "build/sound/direct_sound_samples/cries/latias.aif.bin"

	.align 2
Cry_Wynaut::
	.incbin "build/sound/direct_sound_samples/cries/wynaut.aif.bin"

	.align 2
Cry_Seviper::
	.incbin "build/sound/direct_sound_samples/cries/seviper.aif.bin"

	.align 2
Cry_Sharpedo::
	.incbin "build/sound/direct_sound_samples/cries/sharpedo.aif.bin"

	.align 2
Cry_Zangoose::
	.incbin "build/sound/direct_sound_samples/cries/zangoose.aif.bin"

	.align 2
Cry_Azurill::
	.incbin "build/sound/direct_sound_samples/cries/azurill.aif.bin"

	.align 2
Cry_Swablu::
	.incbin "build/sound/direct_sound_samples/cries/swablu.aif.bin"

	.align 2
Cry_Altaria::
	.incbin "build/sound/direct_sound_samples/cries/altaria.aif.bin"

	.align 2
Cry_Unused265::
	.incbin "build/sound/direct_sound_samples/cries/unused_265.aif.bin"

	.align 2
Cry_Taillow::
	.incbin "build/sound/direct_sound_samples/cries/taillow.aif.bin"

	.align 2
Cry_Swellow::
	.incbin "build/sound/direct_sound_samples/cries/swellow.aif.bin"

	.align 2
Cry_Unused268::
	.incbin "build/sound/direct_sound_samples/cries/unused_268.aif.bin"

	.align 2
Cry_Spinda::
	.incbin "build/sound/direct_sound_samples/cries/spinda.aif.bin"

	.align 2
Cry_Torchic::
	.incbin "build/sound/direct_sound_samples/cries/torchic.aif.bin"

	.align 2
Cry_Combusken::
	.incbin "build/sound/direct_sound_samples/cries/combusken.aif.bin"

	.align 2
Cry_Blaziken::
	.incbin "build/sound/direct_sound_samples/cries/blaziken.aif.bin"

	.align 2
Cry_Treecko::
	.incbin "build/sound/direct_sound_samples/cries/treecko.aif.bin"

	.align 2
Cry_Grovyle::
	.incbin "build/sound/direct_sound_samples/cries/grovyle.aif.bin"

	.align 2
Cry_Sceptile::
	.incbin "build/sound/direct_sound_samples/cries/sceptile.aif.bin"

	.align 2
Cry_Mudkip::
	.incbin "build/sound/direct_sound_samples/cries/mudkip.aif.bin"

	.align 2
Cry_Marshtomp::
	.incbin "build/sound/direct_sound_samples/cries/marshtomp.aif.bin"

	.align 2
Cry_Swampert::
	.incbin "build/sound/direct_sound_samples/cries/swampert.aif.bin"

	.align 2
Cry_Pelipper::
	.incbin "build/sound/direct_sound_samples/cries/pelipper.aif.bin"

	.align 2
Cry_Wingull::
	.incbin "build/sound/direct_sound_samples/cries/wingull.aif.bin"

	.align 2
Cry_Banette::
	.incbin "build/sound/direct_sound_samples/cries/banette.aif.bin"

	.align 2
Cry_Shuppet::
	.incbin "build/sound/direct_sound_samples/cries/shuppet.aif.bin"

	.align 2
Cry_Lotad::
	.incbin "build/sound/direct_sound_samples/cries/lotad.aif.bin"

	.align 2
Cry_Lombre::
	.incbin "build/sound/direct_sound_samples/cries/lombre.aif.bin"

	.align 2
Cry_Ludicolo::
	.incbin "build/sound/direct_sound_samples/cries/ludicolo.aif.bin"

	.align 2
Cry_Seedot::
	.incbin "build/sound/direct_sound_samples/cries/seedot.aif.bin"

	.align 2
Cry_Nuzleaf::
	.incbin "build/sound/direct_sound_samples/cries/nuzleaf.aif.bin"

	.align 2
Cry_Shiftry::
	.incbin "build/sound/direct_sound_samples/cries/shiftry.aif.bin"

	.align 2
Cry_Carvanha::
	.incbin "build/sound/direct_sound_samples/cries/carvanha.aif.bin"

	.align 2
Cry_Wurmple::
	.incbin "build/sound/direct_sound_samples/cries/wurmple.aif.bin"

	.align 2
Cry_Silcoon::
	.incbin "build/sound/direct_sound_samples/cries/silcoon.aif.bin"

	.align 2
Cry_Beautifly::
	.incbin "build/sound/direct_sound_samples/cries/beautifly.aif.bin"

	.align 2
Cry_Cascoon::
	.incbin "build/sound/direct_sound_samples/cries/cascoon.aif.bin"

	.align 2
Cry_Dustox::
	.incbin "build/sound/direct_sound_samples/cries/dustox.aif.bin"

	.align 2
Cry_Ralts::
	.incbin "build/sound/direct_sound_samples/cries/ralts.aif.bin"

	.align 2
Cry_Kirlia::
	.incbin "build/sound/direct_sound_samples/cries/kirlia.aif.bin"

	.align 2
Cry_Gardevoir::
	.incbin "build/sound/direct_sound_samples/cries/gardevoir.aif.bin"

	.align 2
Cry_Slakoth::
	.incbin "build/sound/direct_sound_samples/cries/slakoth.aif.bin"

	.align 2
Cry_Vigoroth::
	.incbin "build/sound/direct_sound_samples/cries/vigoroth.aif.bin"

	.align 2
Cry_Slaking::
	.incbin "build/sound/direct_sound_samples/cries/slaking.aif.bin"

	.align 2
Cry_Nincada::
	.incbin "build/sound/direct_sound_samples/cries/nincada.aif.bin"

	.align 2
Cry_Ninjask::
	.incbin "build/sound/direct_sound_samples/cries/ninjask.aif.bin"

	.align 2
Cry_Shedinja::
	.incbin "build/sound/direct_sound_samples/cries/shedinja.aif.bin"

	.align 2
Cry_Makuhita::
	.incbin "build/sound/direct_sound_samples/cries/makuhita.aif.bin"

	.align 2
Cry_Hariyama::
	.incbin "build/sound/direct_sound_samples/cries/hariyama.aif.bin"

	.align 2
Cry_Nosepass::
	.incbin "build/sound/direct_sound_samples/cries/nosepass.aif.bin"

	.align 2
Cry_Glalie::
	.incbin "build/sound/direct_sound_samples/cries/glalie.aif.bin"

	.align 2
Cry_Plusle::
	.incbin "build/sound/direct_sound_samples/cries/plusle.aif.bin"

	.align 2
Cry_Minun::
	.incbin "build/sound/direct_sound_samples/cries/minun.aif.bin"

	.align 2
Cry_Surskit::
	.incbin "build/sound/direct_sound_samples/cries/surskit.aif.bin"

	.align 2
Cry_Masquerain::
	.incbin "build/sound/direct_sound_samples/cries/masquerain.aif.bin"

	.align 2
Cry_Skitty::
	.incbin "build/sound/direct_sound_samples/cries/skitty.aif.bin"

	.align 2
Cry_Delcatty::
	.incbin "build/sound/direct_sound_samples/cries/delcatty.aif.bin"

	.align 2
Cry_Gulpin::
	.incbin "build/sound/direct_sound_samples/cries/gulpin.aif.bin"

	.align 2
Cry_Swalot::
	.incbin "build/sound/direct_sound_samples/cries/swalot.aif.bin"

	.align 2
Cry_Numel::
	.incbin "build/sound/direct_sound_samples/cries/numel.aif.bin"

	.align 2
Cry_Camerupt::
	.incbin "build/sound/direct_sound_samples/cries/camerupt.aif.bin"

	.align 2
Cry_Barboach::
	.incbin "build/sound/direct_sound_samples/cries/barboach.aif.bin"

	.align 2
Cry_Whiscash::
	.incbin "build/sound/direct_sound_samples/cries/whiscash.aif.bin"

	.align 2
Cry_Corphish::
	.incbin "build/sound/direct_sound_samples/cries/corphish.aif.bin"

	.align 2
Cry_Crawdaunt::
	.incbin "build/sound/direct_sound_samples/cries/crawdaunt.aif.bin"

	.align 2
Cry_Spoink::
	.incbin "build/sound/direct_sound_samples/cries/spoink.aif.bin"

	.align 2
Cry_Grumpig::
	.incbin "build/sound/direct_sound_samples/cries/grumpig.aif.bin"

	.align 2
Cry_Trapinch::
	.incbin "build/sound/direct_sound_samples/cries/trapinch.aif.bin"

	.align 2
Cry_Vibrava::
	.incbin "build/sound/direct_sound_samples/cries/vibrava.aif.bin"

	.align 2
Cry_Flygon::
	.incbin "build/sound/direct_sound_samples/cries/flygon.aif.bin"

	.align 2
Cry_Cacnea::
	.incbin "build/sound/direct_sound_samples/cries/cacnea.aif.bin"

	.align 2
Cry_Cacturne::
	.incbin "build/sound/direct_sound_samples/cries/cacturne.aif.bin"

	.align 2
Cry_Baltoy::
	.incbin "build/sound/direct_sound_samples/cries/baltoy.aif.bin"

	.align 2
Cry_Claydol::
	.incbin "build/sound/direct_sound_samples/cries/claydol.aif.bin"

	.align 2
Cry_Lunatone::
	.incbin "build/sound/direct_sound_samples/cries/lunatone.aif.bin"

	.align 2
Cry_Solrock::
	.incbin "build/sound/direct_sound_samples/cries/solrock.aif.bin"

	.align 2
Cry_Feebas::
	.incbin "build/sound/direct_sound_samples/cries/feebas.aif.bin"

	.align 2
Cry_Milotic::
	.incbin "build/sound/direct_sound_samples/cries/milotic.aif.bin"

	.align 2
Cry_Absol::
	.incbin "build/sound/direct_sound_samples/cries/absol.aif.bin"

	.align 2
Cry_Meditite::
	.incbin "build/sound/direct_sound_samples/cries/meditite.aif.bin"

	.align 2
Cry_Medicham::
	.incbin "build/sound/direct_sound_samples/cries/medicham.aif.bin"

	.align 2
Cry_Spheal::
	.incbin "build/sound/direct_sound_samples/cries/spheal.aif.bin"

	.align 2
Cry_Sealeo::
	.incbin "build/sound/direct_sound_samples/cries/sealeo.aif.bin"

	.align 2
Cry_Walrein::
	.incbin "build/sound/direct_sound_samples/cries/walrein.aif.bin"

	.align 2
Cry_Clamperl::
	.incbin "build/sound/direct_sound_samples/cries/clamperl.aif.bin"

	.align 2
Cry_Huntail::
	.incbin "build/sound/direct_sound_samples/cries/huntail.aif.bin"

	.align 2
Cry_Gorebyss::
	.incbin "build/sound/direct_sound_samples/cries/gorebyss.aif.bin"

	.align 2
Cry_Lileep::
	.incbin "build/sound/direct_sound_samples/cries/lileep.aif.bin"

	.align 2
Cry_Cradily::
	.incbin "build/sound/direct_sound_samples/cries/cradily.aif.bin"

	.align 2
Cry_Anorith::
	.incbin "build/sound/direct_sound_samples/cries/anorith.aif.bin"

	.align 2
Cry_Armaldo::
	.incbin "build/sound/direct_sound_samples/cries/armaldo.aif.bin"

	.align 2
Cry_Beldum::
	.incbin "build/sound/direct_sound_samples/cries/beldum.aif.bin"

	.align 2
Cry_Metang::
	.incbin "build/sound/direct_sound_samples/cries/metang.aif.bin"

	.align 2
Cry_Metagross::
	.incbin "build/sound/direct_sound_samples/cries/metagross.aif.bin"

	.align 2
Cry_Bagon::
	.incbin "build/sound/direct_sound_samples/cries/bagon.aif.bin"

	.align 2
Cry_Shelgon::
	.incbin "build/sound/direct_sound_samples/cries/shelgon.aif.bin"

	.align 2
Cry_Regirock::
	.incbin "build/sound/direct_sound_samples/cries/regirock.aif.bin"

	.align 2
Cry_Regice::
	.incbin "build/sound/direct_sound_samples/cries/regice.aif.bin"

	.align 2
Cry_Registeel::
	.incbin "build/sound/direct_sound_samples/cries/registeel.aif.bin"

	.align 2
Cry_Castform::
	.incbin "build/sound/direct_sound_samples/cries/castform.aif.bin"

	.align 2
Cry_Volbeat::
	.incbin "build/sound/direct_sound_samples/cries/volbeat.aif.bin"

	.align 2
Cry_Illumise::
	.incbin "build/sound/direct_sound_samples/cries/illumise.aif.bin"

	.align 2
Cry_Poochyena::
	.incbin "build/sound/direct_sound_samples/cries/poochyena.aif.bin"

	.align 2
Cry_Mightyena::
	.incbin "build/sound/direct_sound_samples/cries/mightyena.aif.bin"

	.align 2
Cry_Dusclops::
	.incbin "build/sound/direct_sound_samples/cries/dusclops.aif.bin"

	.align 2
Cry_Sableye::
	.incbin "build/sound/direct_sound_samples/cries/sableye.aif.bin"

	.align 2
Cry_Mawile::
	.incbin "build/sound/direct_sound_samples/cries/mawile.aif.bin"

	.align 2
Cry_Aron::
	.incbin "build/sound/direct_sound_samples/cries/aron.aif.bin"

	.align 2
Cry_Lairon::
	.incbin "build/sound/direct_sound_samples/cries/lairon.aif.bin"

	.align 2
Cry_Aggron::
	.incbin "build/sound/direct_sound_samples/cries/aggron.aif.bin"

	.align 2
Cry_Relicanth::
	.incbin "build/sound/direct_sound_samples/cries/relicanth.aif.bin"

	.align 2
Cry_Luvdisc::
	.incbin "build/sound/direct_sound_samples/cries/luvdisc.aif.bin"

	.align 2
Cry_Groudon::
	.incbin "build/sound/direct_sound_samples/cries/groudon.aif.bin"

	.align 2
Cry_Kyogre::
	.incbin "build/sound/direct_sound_samples/cries/kyogre.aif.bin"

	.align 2
Cry_Rayquaza::
	.incbin "build/sound/direct_sound_samples/cries/rayquaza.aif.bin"

	.align 2
Cry_Salamence::
	.incbin "build/sound/direct_sound_samples/cries/salamence.aif.bin"

	.align 2
Cry_Breloom::
	.incbin "build/sound/direct_sound_samples/cries/breloom.aif.bin"

	.align 2
Cry_Shroomish::
	.incbin "build/sound/direct_sound_samples/cries/shroomish.aif.bin"

	.align 2
Cry_Linoone::
	.incbin "build/sound/direct_sound_samples/cries/linoone.aif.bin"

	.align 2
Cry_Tropius::
	.incbin "build/sound/direct_sound_samples/cries/tropius.aif.bin"

	.align 2
Cry_Wailmer::
	.incbin "build/sound/direct_sound_samples/cries/wailmer.aif.bin"

	.align 2
Cry_Zigzagoon::
	.incbin "build/sound/direct_sound_samples/cries/zigzagoon.aif.bin"

	.align 2
Cry_Exploud::
	.incbin "build/sound/direct_sound_samples/cries/exploud.aif.bin"

	.align 2
Cry_Loudred::
	.incbin "build/sound/direct_sound_samples/cries/loudred.aif.bin"

	.align 2
Cry_Wailord::
	.incbin "build/sound/direct_sound_samples/cries/wailord.aif.bin"

	.align 2
Cry_Whismur::
	.incbin "build/sound/direct_sound_samples/cries/whismur.aif.bin"

	.align 2
Cry_Snorunt::
	.incbin "build/sound/direct_sound_samples/cries/snorunt.aif.bin"

	.align 2
Cry_Latios::
	.incbin "build/sound/direct_sound_samples/cries/latios.aif.bin"

	.align 2
Cry_Jirachi::
	.incbin "build/sound/direct_sound_samples/cries/jirachi.aif.bin"

	.align 2
Cry_Deoxys::
	.incbin "build/sound/direct_sound_samples/cries/deoxys.aif.bin"

	.align 2
Cry_Chimecho::
	.incbin "build/sound/direct_sound_samples/cries/chimecho.aif.bin"

	.align 2
DirectSoundWaveData_register_noise::
	.incbin "build/sound/direct_sound_samples/register_noise.aif.bin"

	.align 2
DirectSoundWaveData_unknown_18::
	.incbin "build/sound/direct_sound_samples/unknown_18.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_nylon_str_guitar::
	.incbin "build/sound/direct_sound_samples/sc88pro_nylon_str_guitar.aif.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "build/sound/direct_sound_samples/sd90_special_scream_drive.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_1::
	.incbin "build/sound/direct_sound_samples/phonemes/01.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_2::
	.incbin "build/sound/direct_sound_samples/phonemes/02.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_3::
	.incbin "build/sound/direct_sound_samples/phonemes/03.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_4::
	.incbin "build/sound/direct_sound_samples/phonemes/04.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_5::
	.incbin "build/sound/direct_sound_samples/phonemes/05.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_6::
	.incbin "build/sound/direct_sound_samples/phonemes/06.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_7::
	.incbin "build/sound/direct_sound_samples/phonemes/07.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_8::
	.incbin "build/sound/direct_sound_samples/phonemes/08.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_9::
	.incbin "build/sound/direct_sound_samples/phonemes/09.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_10::
	.incbin "build/sound/direct_sound_samples/phonemes/10.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_11::
	.incbin "build/sound/direct_sound_samples/phonemes/11.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_12::
	.incbin "build/sound/direct_sound_samples/phonemes/12.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_13::
	.incbin "build/sound/direct_sound_samples/phonemes/13.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_14::
	.incbin "build/sound/direct_sound_samples/phonemes/14.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_15::
	.incbin "build/sound/direct_sound_samples/phonemes/15.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_16::
	.incbin "build/sound/direct_sound_samples/phonemes/16.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_17::
	.incbin "build/sound/direct_sound_samples/phonemes/17.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_18::
	.incbin "build/sound/direct_sound_samples/phonemes/18.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_19::
	.incbin "build/sound/direct_sound_samples/phonemes/19.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_20::
	.incbin "build/sound/direct_sound_samples/phonemes/20.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_21::
	.incbin "build/sound/direct_sound_samples/phonemes/21.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_22::
	.incbin "build/sound/direct_sound_samples/phonemes/22.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_23::
	.incbin "build/sound/direct_sound_samples/phonemes/23.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_24::
	.incbin "build/sound/direct_sound_samples/phonemes/24.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_25::
	.incbin "build/sound/direct_sound_samples/phonemes/25.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_26::
	.incbin "build/sound/direct_sound_samples/phonemes/26.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_27::
	.incbin "build/sound/direct_sound_samples/phonemes/27.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_28::
	.incbin "build/sound/direct_sound_samples/phonemes/28.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_29::
	.incbin "build/sound/direct_sound_samples/phonemes/29.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_30::
	.incbin "build/sound/direct_sound_samples/phonemes/30.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_31::
	.incbin "build/sound/direct_sound_samples/phonemes/31.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_32::
	.incbin "build/sound/direct_sound_samples/phonemes/32.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_33::
	.incbin "build/sound/direct_sound_samples/phonemes/33.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_34::
	.incbin "build/sound/direct_sound_samples/phonemes/34.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_35::
	.incbin "build/sound/direct_sound_samples/phonemes/35.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_36::
	.incbin "build/sound/direct_sound_samples/phonemes/36.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_37::
	.incbin "build/sound/direct_sound_samples/phonemes/37.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_38::
	.incbin "build/sound/direct_sound_samples/phonemes/38.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_39::
	.incbin "build/sound/direct_sound_samples/phonemes/39.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_40::
	.incbin "build/sound/direct_sound_samples/phonemes/40.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_41::
	.incbin "build/sound/direct_sound_samples/phonemes/41.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_42::
	.incbin "build/sound/direct_sound_samples/phonemes/42.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_43::
	.incbin "build/sound/direct_sound_samples/phonemes/43.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_44::
	.incbin "build/sound/direct_sound_samples/phonemes/44.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_45::
	.incbin "build/sound/direct_sound_samples/phonemes/45.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_46::
	.incbin "build/sound/direct_sound_samples/phonemes/46.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_47::
	.incbin "build/sound/direct_sound_samples/phonemes/47.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_48::
	.incbin "build/sound/direct_sound_samples/phonemes/48.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_49::
	.incbin "build/sound/direct_sound_samples/phonemes/49.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_50::
	.incbin "build/sound/direct_sound_samples/phonemes/50.aif.bin"

	.align 2
DirectSoundWaveData_Phoneme_51::
	.incbin "build/sound/direct_sound_samples/phonemes/51.aif.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion_duplicate::
	.incbin "build/sound/direct_sound_samples/sc88pro_accordion_duplicate.aif.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "build/sound/direct_sound_samples/steinway_b_piano.aif.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "build/sound/direct_sound_samples/sd90_classical_whistle.aif.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "build/sound/direct_sound_samples/sd90_enhanced_delay_shaku.aif.bin"
